### ISSUE TITLE
Bug: translations not staying for long when using a different language.

### ISSUE THREAD

**Issue by serapieTuyishime** [dacadeorg/dacade-frontend-app#1254] opened 2024-05-30 07:06 UTC
For example, when translating the submission's description to its original language,  the text doesn't stay for long, it defaults back to the current locale language.

https://github.com/dacadeorg/dacade-frontend-app/assets/70019756/18e2e455-49d4-48c9-b309-a01117a84286

**Comment by hunxjunedo** [comment] 2024-05-30 14:25
hey @serapieTuyishime , kindly assign this issue to me, I'd love to contribute to this repository.

**Comment by hunxjunedo** [comment] 2024-05-30 16:08
Thanks, coming back with a pr soon.

**Comment by hunxjunedo** [comment] 2024-05-30 18:11
hey, looks like I'll need admin credentials to reproduce the issue.

**Comment by hunxjunedo** [comment] 2024-05-30 18:18
hey i looked into it, do you have a Google translate API while this issue occurred ? because the env variables on the repo's main page are missing the Google translate api key, and therefore it can't translate.

**Closed** 2024-07-02 10:56 UTC
Labels: bug
